dummyjson.api : https://dummyjson.com

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springsecurity
    username: mehrab
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop